### ISSUE TITLE
enketo.getodk.org version mismatch

### ISSUE THREAD

**Issue by jnm** [getodk/xlsform-online#42]
Hello and apologies if this is something that's already being discussed with @MartijnR.

It seems like although https://enketo.getodk.org/ reports `version: 2.6.2`, some portion of it is using code older than 2.6.0, i.e. some version prior to Enketo's switch to a new XPath evaluator.

For context, I was trying to reproduce [an issue](https://github.com/enketo/openrosa-xpath-evaluator/issues/81) by using the Enketo preview on https://getodk.org/xlsform/, and was puzzled by seeing it behave differently than my own installation of Enketo 2.6.2. I asked Martijn if he knew what I was doing wrong, and he thought that the deployment of 2.6.2 here might be incomplete.

**Comment by yanokwa** [comment]
Martin pinged me yesterday, but my memory isn't so good these days, so thanks for filing the issue!

It seems impossible things are happening. I'll follow up with him to see if we can track it down.

**Comment by yanokwa** [comment]
I think it's working now? If you can provide me a test form to verify, I'm glad to confirm it. Or you can also verify it yourself and have the joy of knowing it's fixed before anyone else.

**Comment by yanokwa** [comment]
I believe enketo.getodk.org is now running master (2.6.2-3-gc948d1c) and will continue to update daily as before.

According to @MartijnR, the issue with toomanytokens is a bug in the XPath library that will be fixed soon.

**Comment by jnm** [comment]
Hey, it's one of those times where seeing an error message is a good thing :grin:
