### ISSUE TITLE
Forms with unicode filenames fail conversion

### ISSUE THREAD

**Issue by yanokwa** [getodk/xlsform-online#43]
Related? https://github.com/getodk/central/issues/196

**Comment by matthew-white** [comment]
I took a quick look at this, and I think it's a slightly different issue. I think here XLSForm Online needs to percent-encode the filename in the URL.

However, an Enketo change is maybe also required. When I encode the filename in the preview URL that XLSForm Online generates, Enketo no longer says, "Bad Request. Server URL is not a valid URL." However, the loading animation seems to continue indefinitely, and I see a different error in the console:

```
Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at enketo-webform-bundle.min.js:8
```

**Comment by matthew-white** [comment]
Let me know if it'd be helpful to file an Enketo issue!
